services:
  registry:
    image: registry
    container_name: registry
    environment:
      - MCP_PORT=8080
      - MCP_HOST=0.0.0.0
      - MCP_ENVIRONMENT=${MCP_ENVIRONMENT:-dev}
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-info}
      - MCP_STORAGE_TYPE=${MCP_STORAGE_TYPE:-sqlite}
      - MCP_DATA_PATH=/app/data
      - MCP_DATABASE_URL=/app/data/registry.db
    volumes:
      - ./data:/app/data
    ports:
      - 8080:8080
    restart: "unless-stopped"
